feat: update Vagrantfile and add setup script

diff --git a/.gitlab/gitlab-runner/vm/Vagrantfile b/.gitlab/gitlab-runner/vm/Vagrantfile
--- a/.gitlab/gitlab-runner/vm/Vagrantfile
+++ b/.gitlab/gitlab-runner/vm/Vagrantfile
@@ -14,8 +14,8 @@ boxes = [
     :vm_cpu => "2",
     :box_name => "net9/ubuntu-24.04-arm64",
     :box_version => "1.1",
-    :network_hostname => "gitlab-runner.develop.local",
-    :network_hostname_aliases => ["gitlab-runner.develop.local"],
+    :network_hostname => "gitlab-runner.local",
+    :network_hostname_aliases => ["gitlab-runner.develop.x9x"],
     :network_private_ip => "172.16.16.10",
     :network_private_netmask => "255.255.255.0",
     :network_public_ip => "192.168.31.100",
@@ -45,8 +45,13 @@ Vagrant.configure("2") do |config|
 
     # configure plugin
     case plugin_name
+    when 'vagrant-hostmanager'
+      config.hostmanager.enabled = false
+      config.hostmanager.manage_host = true
+      config.hostmanager.manage_guest = true
+      config.hostmanager.include_offline = true
+      config.hostmanager.ignore_private_ip = false
     when 'vagrant-vbguest'
-      puts "configuring plugin #{plugin_name}"
       config.vbguest.auto_update = false
       config.vbguest.installer_options = { allow_kernel_upgrade: false }
     else
@@ -77,7 +82,7 @@ Vagrant.configure("2") do |config|
       guest_config.vm.network 'private_network', ip: opts[:network_private_ip]
       # guest_config.vm.network 'public_network', type: 'dhcp', bridge: opts[:network_public_bridge]
       guest_config.vm.network 'public_network', ip: opts[:network_public_ip], bridge: opts[:network_public_bridge]
-      # guest_config.hostmanager.aliases = opts[:network_hostname_aliases]
+      guest_config.hostmanager.aliases = opts[:network_hostname_aliases]
 
       # 2.4 挂载
       guest_config.vm.synced_folder opts[:synced_folder_host_path], opts[:synced_folder_mount_path], create: opts[:synced_folder_create]
@@ -86,7 +91,34 @@ Vagrant.configure("2") do |config|
       # guest_config.vm.network 'forwarded_port', guest: opts[:forwarded_port_guest], host: opts[:forwarded_port_host]
 
       # 2.6 run script/file
-      # guest_config.vm.provision "shell", privileged: true, path: "./setup.sh"
+      if plugins.include?("vagrant-hostmanager")
+        # Execute the hostmanager provisioner
+        config.vm.provision :hostmanager
+      end
+
+      host_public_key_path = File.expand_path("~/.ssh/keys/id_rsa_vagrant.pub")
+      unless File.exist?(host_public_key_path)
+        abort("Error: Public key not found at #{host_public_key_path}. Please generate it using `ssh-keygen`.")
+      end
+      # Read the public key content
+      host_public_key = File.read(host_public_key_path).strip
+      guest_config.vm.provision "shell", privileged: false, run: "once", inline: <<-SHELL
+        # Ensure the .ssh directory exists
+        mkdir -p ~/.ssh
+      
+        # Append the public key to authorized_keys if it's not already present
+        if ! grep -q "#{host_public_key}" ~/.ssh/authorized_keys 2>/dev/null; then
+          echo "#{host_public_key}" >> ~/.ssh/authorized_keys
+          echo "Public key appended to ~/.ssh/authorized_keys."
+        else
+          echo "Public key already exists in ~/.ssh/authorized_keys."
+        fi
+      
+        # Set the correct permissions
+        chmod 700 ~/.ssh
+        chmod 600 ~/.ssh/authorized_keys
+      SHELL
+      guest_config.vm.provision "shell", privileged: false, path: "./setup.sh"
     end
   end
 end
